# Generated by Django 2.0.7 on 2018-07-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Words',
        ),
    ]
